name: Lint PR
on:
  pull_request:
    types:
      - opened
      - synchronize # when PR branch is updated
      - reopened

# only run one workflow at a time and kill the others
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name != 'status' || github.event.state == 'success') }}
    steps:
      - name: info
        run: |
          echo "EVENT_NAME: $EVENT_NAME"
          echo "STATUS_STATE: $STATUS_STATE"
          echo "event.context: $EVENT_CONTEXT"
          echo "REPO: $REPO"
          echo "PR_SHA: $PR_SHA"
          echo "STATUS_SHA: $STATUS_SHA"
          echo "REF: $REF"
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"
          echo "JOB_CONTEXT: $JOB_CONTEXT"
          echo "STEPS_CONTEXT: $STEPS_CONTEXT"
          echo "RUNNER_CONTEXT: $RUNNER_CONTEXT"
          echo "STRATEGY_CONTEXT: $STRATEGY_CONTEXT"
          echo "MATRIX_CONTEXT: $MATRIX_CONTEXT"
          echo "contents of GITHUB_EVENT_PATH file:"
          cat $GITHUB_EVENT_PATH
        env:
          EVENT_NAME: "${{ github.event_name }}"
          STATUS_STATE: "${{ github.event.state }}"
          EVENT_CONTEXT: "${{ github.event.context }}"
          REPO: "${{ github.repository }}"
          PR_SHA: "${{ github.event.pull_request.head.sha }}"
          STATUS_SHA: "${{ github.event.sha }}"
          REF: "${{ github.ref }}"
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
